# Generated by Django 5.1.1 on 2025-04-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=400)),
                ('bachelor_clg', models.CharField(max_length=400)),
                ('masters_clg', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_subj', models.CharField(max_length=50)),
                ('teacher_class', models.CharField(max_length=10)),
                ('teacher_section', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_comm_skill', models.CharField(max_length=10)),
                ('teacher_class_mgt_skill', models.CharField(max_length=10)),
                ('teacher_subj_skill', models.CharField(max_length=10)),
                ('teacher_creativity_skill', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_first_name', models.CharField(max_length=100)),
                ('teacher_last_name', models.CharField(max_length=100)),
                ('teacher_email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('teacher_dob', models.DateField()),
                ('teacher_mobile', models.CharField(max_length=20)),
                ('teacher_join_date', models.DateField()),
                ('teacher_qualification', models.CharField(max_length=100)),
                ('teacher_experience', models.CharField(max_length=10)),
                ('teacher_address', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('teacher_achievements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.achievements')),
                ('teacher_education', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.education')),
                ('teacher_responsibility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.responsibility')),
                ('teacher_skills', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.skills')),
            ],
        ),
    ]
