# Generated by Django 5.1.1 on 2025-04-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_teacher_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_achievements',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_education',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.education'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_responsibility',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.responsibility'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.skills'),
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
