# Generated by Django 5.1.1 on 2025-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20)),
                ('room_no', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('Normal', 'Normal'), ('AC', 'AC'), ('Suite', 'Suite')], max_length=50)),
                ('no_of_beds', models.CharField(max_length=5)),
                ('cost_per_bed', models.CharField(max_length=50)),
                ('room_status', models.CharField(choices=[('Full', 'Full'), ('Available', 'Available')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_id', models.CharField(max_length=20)),
                ('sports_name', models.CharField(max_length=50)),
                ('coach_name', models.CharField(max_length=100)),
                ('start_year', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('vehicle_num', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('license_num', models.CharField(max_length=20)),
                ('driver_mobile', models.CharField(max_length=10)),
                ('driver_address', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
