# Generated by Django 5.2 on 2025-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mgt2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
