# Generated by Django 5.1.1 on 2025-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mgt2', '0002_happenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_class', models.CharField(max_length=5)),
                ('lec_section', models.CharField(max_length=5)),
                ('lec_date', models.DateField()),
                ('lec_start_time', models.TimeField()),
                ('lec_end_time', models.TimeField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
