# Generated by Django 5.2 on 2025-04-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home_page', '0004_alter_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
