# Generated by Django 5.2 on 2025-04-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home_page', '0005_alter_activity_name'),
        ('student', '0004_alter_parent_father_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
