# Generated by Django 5.1.1 on 2025-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_class', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('exam_start_time', models.TimeField()),
                ('exam_end_time', models.TimeField()),
                ('exam_date', models.DateField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_id', models.CharField(max_length=20)),
                ('holiday_name', models.CharField(max_length=50)),
                ('holiday_type', models.CharField(choices=[('Public Holiday', 'Public Holiday'), ('College Holiday', 'College Holiday'), ('Exam Holiday', 'Exam Holiday'), ('Others', 'Others')], max_length=30)),
                ('holiday_start_date', models.DateField()),
                ('holiday_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=20)),
                ('book_name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Gujarati')], max_length=20)),
                ('book_class', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('article_type', models.CharField(choices=[('Book', 'Book'), ('DVD', 'DVD'), ('CD', 'CD'), ('Newspaper', 'Newspaper'), ('Magazine', 'Magazine')], max_length=20)),
                ('book_status', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20)),
                ('teacher_name', models.CharField(max_length=100)),
                ('lec_class', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('lec_section', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('lec_date', models.DateField()),
                ('lec_start_time', models.TimeField()),
                ('lec_end_time', models.TimeField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
