# Generated by Django 5.2 on 2025-04-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=20)),
                ('father_email', models.EmailField(max_length=50, unique=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=20)),
                ('mother_email', models.EmailField(max_length=50)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=50, unique=True)),
                ('student_id', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('student_dob', models.DateField()),
                ('student_class', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('admission_number', models.CharField(max_length=50)),
                ('student_section', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.parent')),
            ],
        ),
    ]
