# Generated by Django 5.2 on 2025-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_skills_student_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='father_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
