# Generated by Django 5.2 on 2025-04-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
